// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package genproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Sync with code_generator.h.
type CodeGeneratorResponse_Feature int32

const (
	CodeGeneratorResponse_FEATURE_NONE            CodeGeneratorResponse_Feature = 0
	CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL CodeGeneratorResponse_Feature = 1
)

var CodeGeneratorResponse_Feature_name = map[int32]string{
	0: "FEATURE_NONE",
	1: "FEATURE_PROTO3_OPTIONAL",
}

var CodeGeneratorResponse_Feature_value = map[string]int32{
	"FEATURE_NONE":            0,
	"FEATURE_PROTO3_OPTIONAL": 1,
}

func (x CodeGeneratorResponse_Feature) Enum() *CodeGeneratorResponse_Feature {
	p := new(CodeGeneratorResponse_Feature)
	*p = x
	return p
}

func (x CodeGeneratorResponse_Feature) String() string {
	return proto.EnumName(CodeGeneratorResponse_Feature_name, int32(x))
}

func (x *CodeGeneratorResponse_Feature) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CodeGeneratorResponse_Feature_value, data, "CodeGeneratorResponse_Feature")
	if err != nil {
		return err
	}
	*x = CodeGeneratorResponse_Feature(value)
	return nil
}

func (CodeGeneratorResponse_Feature) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2, 0}
}

// The version number of protocol compiler.
type Version struct {
	Major *int32 `protobuf:"varint,1,opt,name=major" json:"major,omitempty"`
	Minor *int32 `protobuf:"varint,2,opt,name=minor" json:"minor,omitempty"`
	Patch *int32 `protobuf:"varint,3,opt,name=patch" json:"patch,omitempty"`
	// A suffix for alpha, beta or rc release, e.g., "alpha-1", "rc2". It should
	// be empty for mainline stable releases.
	Suffix               *string  `protobuf:"bytes,4,opt,name=suffix" json:"suffix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetMajor() int32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return 0
}

func (m *Version) GetMinor() int32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return 0
}

func (m *Version) GetPatch() int32 {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return 0
}

func (m *Version) GetSuffix() string {
	if m != nil && m.Suffix != nil {
		return *m.Suffix
	}
	return ""
}

// An encoded CodeGeneratorRequest is written to the plugin's stdin.
type CodeGeneratorRequest struct {
	// The .proto files that were explicitly listed on the command-line.  The
	// code generator should generate code only for these files.  Each file's
	// descriptor will be included in proto_file, below.
	FileToGenerate []string `protobuf:"bytes,1,rep,name=file_to_generate,json=fileToGenerate" json:"file_to_generate,omitempty"`
	// The generator parameter passed on the command-line.
	Parameter *string `protobuf:"bytes,2,opt,name=parameter" json:"parameter,omitempty"`
	// FileDescriptorProtos for all files in files_to_generate and everything
	// they import.  The files will appear in topological order, so each file
	// appears before any file that imports it.
	//
	// protoc guarantees that all proto_files will be written after
	// the fields above, even though this is not technically guaranteed by the
	// protobuf wire format.  This theoretically could allow a plugin to stream
	// in the FileDescriptorProtos and handle them one by one rather than read
	// the entire set into memory at once.  However, as of this writing, this
	// is not similarly optimized on protoc's end -- it will store all fields in
	// memory at once before sending them to the plugin.
	//
	// Type names of fields and extensions in the FileDescriptorProto are always
	// fully qualified.
	ProtoFile []*FileDescriptorProto `protobuf:"bytes,15,rep,name=proto_file,json=protoFile" json:"proto_file,omitempty"`
	// The version number of protocol compiler.
	CompilerVersion      *Version `protobuf:"bytes,3,opt,name=compiler_version,json=compilerVersion" json:"compiler_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeGeneratorRequest) Reset()         { *m = CodeGeneratorRequest{} }
func (m *CodeGeneratorRequest) String() string { return proto.CompactTextString(m) }
func (*CodeGeneratorRequest) ProtoMessage()    {}
func (*CodeGeneratorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *CodeGeneratorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeGeneratorRequest.Unmarshal(m, b)
}
func (m *CodeGeneratorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeGeneratorRequest.Marshal(b, m, deterministic)
}
func (m *CodeGeneratorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeGeneratorRequest.Merge(m, src)
}
func (m *CodeGeneratorRequest) XXX_Size() int {
	return xxx_messageInfo_CodeGeneratorRequest.Size(m)
}
func (m *CodeGeneratorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeGeneratorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CodeGeneratorRequest proto.InternalMessageInfo

func (m *CodeGeneratorRequest) GetFileToGenerate() []string {
	if m != nil {
		return m.FileToGenerate
	}
	return nil
}

func (m *CodeGeneratorRequest) GetParameter() string {
	if m != nil && m.Parameter != nil {
		return *m.Parameter
	}
	return ""
}

func (m *CodeGeneratorRequest) GetProtoFile() []*FileDescriptorProto {
	if m != nil {
		return m.ProtoFile
	}
	return nil
}

func (m *CodeGeneratorRequest) GetCompilerVersion() *Version {
	if m != nil {
		return m.CompilerVersion
	}
	return nil
}

// The plugin writes an encoded CodeGeneratorResponse to stdout.
type CodeGeneratorResponse struct {
	// Error message.  If non-empty, code generation failed.  The plugin process
	// should exit with status code zero even if it reports an error in this way.
	//
	// This should be used to indicate errors in .proto files which prevent the
	// code generator from generating correct code.  Errors which indicate a
	// problem in protoc itself -- such as the input CodeGeneratorRequest being
	// unparseable -- should be reported by writing a message to stderr and
	// exiting with a non-zero status code.
	Error *string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	// A bitmask of supported features that the code generator supports.
	// This is a bitwise "or" of values from the Feature enum.
	SupportedFeatures    *uint64                       `protobuf:"varint,2,opt,name=supported_features,json=supportedFeatures" json:"supported_features,omitempty"`
	File                 []*CodeGeneratorResponse_File `protobuf:"bytes,15,rep,name=file" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CodeGeneratorResponse) Reset()         { *m = CodeGeneratorResponse{} }
func (m *CodeGeneratorResponse) String() string { return proto.CompactTextString(m) }
func (*CodeGeneratorResponse) ProtoMessage()    {}
func (*CodeGeneratorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *CodeGeneratorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeGeneratorResponse.Unmarshal(m, b)
}
func (m *CodeGeneratorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeGeneratorResponse.Marshal(b, m, deterministic)
}
func (m *CodeGeneratorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeGeneratorResponse.Merge(m, src)
}
func (m *CodeGeneratorResponse) XXX_Size() int {
	return xxx_messageInfo_CodeGeneratorResponse.Size(m)
}
func (m *CodeGeneratorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeGeneratorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CodeGeneratorResponse proto.InternalMessageInfo

func (m *CodeGeneratorResponse) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *CodeGeneratorResponse) GetSupportedFeatures() uint64 {
	if m != nil && m.SupportedFeatures != nil {
		return *m.SupportedFeatures
	}
	return 0
}

func (m *CodeGeneratorResponse) GetFile() []*CodeGeneratorResponse_File {
	if m != nil {
		return m.File
	}
	return nil
}

// Represents a single generated file.
type CodeGeneratorResponse_File struct {
	// The file name, relative to the output directory.  The name must not
	// contain "." or ".." components and must be relative, not be absolute (so,
	// the file cannot lie outside the output directory).  "/" must be used as
	// the path separator, not "\".
	//
	// If the name is omitted, the content will be appended to the previous
	// file.  This allows the generator to break large files into small chunks,
	// and allows the generated text to be streamed back to protoc so that large
	// files need not reside completely in memory at one time.  Note that as of
	// this writing protoc does not optimize for this -- it will read the entire
	// CodeGeneratorResponse before writing files to disk.
	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// If non-empty, indicates that the named file should already exist, and the
	// content here is to be inserted into that file at a defined insertion
	// point.  This feature allows a code generator to extend the output
	// produced by another code generator.  The original generator may provide
	// insertion points by placing special annotations in the file that look
	// like:
	//   @@protoc_insertion_point(NAME)
	// The annotation can have arbitrary text before and after it on the line,
	// which allows it to be placed in a comment.  NAME should be replaced with
	// an identifier naming the point -- this is what other generators will use
	// as the insertion_point.  Code inserted at this point will be placed
	// immediately above the line containing the insertion point (thus multiple
	// insertions to the same point will come out in the order they were added).
	// The double-@ is intended to make it unlikely that the generated code
	// could contain things that look like insertion points by accident.
	//
	// For example, the C++ code generator places the following line in the
	// .pb.h files that it generates:
	//   // @@protoc_insertion_point(namespace_scope)
	// This line appears within the scope of the file's package namespace, but
	// outside of any particular class.  Another plugin can then specify the
	// insertion_point "namespace_scope" to generate additional classes or
	// other declarations that should be placed in this scope.
	//
	// Note that if the line containing the insertion point begins with
	// whitespace, the same whitespace will be added to every line of the
	// inserted text.  This is useful for languages like Python, where
	// indentation matters.  In these languages, the insertion point comment
	// should be indented the same amount as any inserted code will need to be
	// in order to work correctly in that context.
	//
	// The code generator that generates the initial file and the one which
	// inserts into it must both run as part of a single invocation of protoc.
	// Code generators are executed in the order in which they appear on the
	// command line.
	//
	// If |insertion_point| is present, |name| must also be present.
	InsertionPoint *string `protobuf:"bytes,2,opt,name=insertion_point,json=insertionPoint" json:"insertion_point,omitempty"`
	// The file contents.
	Content *string `protobuf:"bytes,15,opt,name=content" json:"content,omitempty"`
	// Information describing the file content being inserted. If an insertion
	// point is used, this information will be appropriately offset and inserted
	// into the code generation metadata for the generated files.
	GeneratedCodeInfo    *GeneratedCodeInfo `protobuf:"bytes,16,opt,name=generated_code_info,json=generatedCodeInfo" json:"generated_code_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CodeGeneratorResponse_File) Reset()         { *m = CodeGeneratorResponse_File{} }
func (m *CodeGeneratorResponse_File) String() string { return proto.CompactTextString(m) }
func (*CodeGeneratorResponse_File) ProtoMessage()    {}
func (*CodeGeneratorResponse_File) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2, 0}
}

func (m *CodeGeneratorResponse_File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeGeneratorResponse_File.Unmarshal(m, b)
}
func (m *CodeGeneratorResponse_File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeGeneratorResponse_File.Marshal(b, m, deterministic)
}
func (m *CodeGeneratorResponse_File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeGeneratorResponse_File.Merge(m, src)
}
func (m *CodeGeneratorResponse_File) XXX_Size() int {
	return xxx_messageInfo_CodeGeneratorResponse_File.Size(m)
}
func (m *CodeGeneratorResponse_File) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeGeneratorResponse_File.DiscardUnknown(m)
}

var xxx_messageInfo_CodeGeneratorResponse_File proto.InternalMessageInfo

func (m *CodeGeneratorResponse_File) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *CodeGeneratorResponse_File) GetInsertionPoint() string {
	if m != nil && m.InsertionPoint != nil {
		return *m.InsertionPoint
	}
	return ""
}

func (m *CodeGeneratorResponse_File) GetContent() string {
	if m != nil && m.Content != nil {
		return *m.Content
	}
	return ""
}

func (m *CodeGeneratorResponse_File) GetGeneratedCodeInfo() *GeneratedCodeInfo {
	if m != nil {
		return m.GeneratedCodeInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("google.protobuf.compiler.CodeGeneratorResponse_Feature", CodeGeneratorResponse_Feature_name, CodeGeneratorResponse_Feature_value)
	proto.RegisterType((*Version)(nil), "google.protobuf.compiler.Version")
	proto.RegisterType((*CodeGeneratorRequest)(nil), "google.protobuf.compiler.CodeGeneratorRequest")
	proto.RegisterType((*CodeGeneratorResponse)(nil), "google.protobuf.compiler.CodeGeneratorResponse")
	proto.RegisterType((*CodeGeneratorResponse_File)(nil), "google.protobuf.compiler.CodeGeneratorResponse.File")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0x86, 0xaf, 0x6f, 0x52, 0x2a, 0x9f, 0x46, 0x8d, 0x3b, 0x14, 0xb0, 0x4a, 0x17, 0x21, 0x42,
	0x22, 0x9b, 0xc6, 0x52, 0x61, 0x81, 0xc4, 0xaa, 0x2d, 0x09, 0x54, 0xaa, 0x92, 0x68, 0x14, 0x58,
	0xb0, 0xb1, 0x5c, 0xfb, 0xd8, 0x9d, 0x62, 0xcf, 0x19, 0xc6, 0x63, 0xc4, 0x83, 0xf0, 0x22, 0x3c,
	0x1a, 0x6f, 0x80, 0x3c, 0xb6, 0x03, 0x0a, 0x64, 0x37, 0xff, 0xf7, 0x67, 0xac, 0x73, 0x3e, 0xc7,
	0x30, 0x50, 0x79, 0x95, 0x09, 0x39, 0x55, 0x9a, 0x0c, 0x31, 0x3f, 0x23, 0xca, 0x72, 0x6c, 0xd2,
	0x6d, 0x95, 0x4e, 0x63, 0x2a, 0x94, 0xc8, 0x51, 0x9f, 0x78, 0x09, 0x96, 0xb1, 0x16, 0xca, 0x90,
	0x6e, 0xda, 0x71, 0x0c, 0xfb, 0x1f, 0x51, 0x97, 0x82, 0x24, 0x3b, 0x86, 0xbd, 0x22, 0xba, 0x27,
	0xed, 0x3b, 0x23, 0x67, 0xb2, 0xc7, 0x9b, 0x60, 0xa9, 0x90, 0xa4, 0xfd, 0xff, 0x5b, 0x5a, 0x87,
	0x9a, 0xaa, 0xc8, 0xc4, 0x77, 0x7e, 0xaf, 0xa1, 0x36, 0xb0, 0xc7, 0xf0, 0xa0, 0xac, 0xd2, 0x54,
	0x7c, 0xf3, 0xfb, 0x23, 0x67, 0xe2, 0xf2, 0x36, 0x8d, 0x7f, 0x3a, 0x70, 0x7c, 0x45, 0x09, 0xbe,
	0x43, 0x89, 0x3a, 0x32, 0xa4, 0x39, 0x7e, 0xa9, 0xb0, 0x34, 0x6c, 0x02, 0x5e, 0x2a, 0x72, 0x0c,
	0x0d, 0x85, 0x59, 0xd3, 0xa1, 0xef, 0x8c, 0x7a, 0x13, 0x97, 0x1f, 0xd6, 0x7c, 0x4d, 0xed, 0x0d,
	0x64, 0xa7, 0xe0, 0xaa, 0x48, 0x47, 0x05, 0x1a, 0x6c, 0x46, 0x71, 0xf9, 0x6f, 0xc0, 0xae, 0x00,
	0xec, 0x3a, 0x61, 0x7d, 0xcb, 0x1f, 0x8e, 0x7a, 0x93, 0x83, 0xf3, 0xe7, 0xd3, 0x6d, 0x0d, 0x73,
	0x91, 0xe3, 0xdb, 0x8d, 0x80, 0x55, 0x8d, 0xb9, 0x6b, 0xdb, 0xba, 0x61, 0x37, 0xe0, 0x75, 0xa2,
	0xc2, 0xaf, 0x8d, 0x13, 0xbb, 0xde, 0xc1, 0xf9, 0xb3, 0xe9, 0x2e, 0xa3, 0xd3, 0x56, 0x1e, 0x1f,
	0x76, 0xa4, 0x05, 0xe3, 0xef, 0x3d, 0x78, 0xb4, 0xb5, 0x73, 0xa9, 0x48, 0x96, 0x58, 0xbb, 0x43,
	0xad, 0x5b, 0xcf, 0x2e, 0x6f, 0x02, 0x3b, 0x03, 0x56, 0x56, 0x4a, 0x91, 0x36, 0x98, 0x84, 0x29,
	0x46, 0xa6, 0xd2, 0x58, 0xda, 0x4d, 0xfb, 0xfc, 0x68, 0xd3, 0xcc, 0xdb, 0x82, 0xbd, 0x87, 0xfe,
	0x1f, 0xbb, 0xbe, 0xda, 0x3d, 0xe0, 0x3f, 0x67, 0xb0, 0x2a, 0xb8, 0x7d, 0xc2, 0xc9, 0x0f, 0x07,
	0xfa, 0x76, 0x7f, 0x06, 0x7d, 0x19, 0x15, 0xd8, 0x8e, 0x65, 0xcf, 0xec, 0x05, 0x0c, 0x85, 0x2c,
	0x51, 0x1b, 0x41, 0x32, 0x54, 0x24, 0xa4, 0x69, 0xe5, 0x1f, 0x6e, 0xf0, 0xaa, 0xa6, 0xcc, 0x87,
	0xfd, 0x98, 0xa4, 0x41, 0x69, 0xfc, 0xa1, 0xfd, 0x41, 0x17, 0x19, 0x87, 0x87, 0xdd, 0xbb, 0x4d,
	0xc2, 0x98, 0x12, 0x0c, 0x85, 0x4c, 0xc9, 0xf7, 0xac, 0xd9, 0xf1, 0x5f, 0x83, 0x77, 0x6f, 0x3c,
	0xa9, 0x07, 0xbf, 0x96, 0x29, 0xf1, 0xa3, 0x6c, 0x1b, 0x8d, 0x5f, 0xc3, 0x7e, 0x6b, 0x82, 0x79,
	0x30, 0x98, 0xcf, 0x2e, 0xd6, 0x1f, 0xf8, 0x2c, 0x5c, 0x2c, 0x17, 0x33, 0xef, 0x3f, 0xf6, 0x14,
	0x9e, 0x74, 0x64, 0xc5, 0x97, 0xeb, 0xe5, 0xcb, 0x70, 0xb9, 0x5a, 0x5f, 0x2f, 0x17, 0x17, 0x37,
	0x9e, 0x73, 0x69, 0xe0, 0x34, 0xa6, 0x62, 0xa7, 0xae, 0xcb, 0xc1, 0xca, 0x7e, 0x49, 0xf6, 0xcf,
	0x51, 0x7e, 0x9a, 0x67, 0xc2, 0xdc, 0x55, 0xb7, 0x75, 0x1d, 0x14, 0x74, 0x4f, 0x67, 0x79, 0x24,
	0x33, 0x7b, 0x0a, 0x32, 0x0a, 0xd4, 0xe7, 0x2c, 0xe8, 0x2e, 0x06, 0xdd, 0xa3, 0x82, 0xac, 0x93,
	0xfd, 0x66, 0x73, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x05, 0x03, 0x8f, 0xa0, 0x03, 0x00,
	0x00,
}
